spring:
  application:
    name: spring-cloud-producer
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 9003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
